version: '3.8'

services:
  web:
    build: ./app
    # Run unit tests and start the server
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI

volumes:
  postgres_data:
