# Generated by Django 4.2.23 on 2025-06-27 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_user_is_active_user_password_user_reset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mf_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('AUM', models.DecimalField(decimal_places=2, max_digits=20)),
                ('exit_load', models.CharField(max_length=255)),
                ('expense_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('Debt', 'Debt'), ('Equity', 'Equity'), ('Hybrid', 'Hybrid'), ('Others', 'Others')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mutualfunds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFHolding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('holding_id', models.CharField(max_length=100, unique=True)),
                ('NAV', models.DecimalField(decimal_places=4, max_digits=12)),
                ('units', models.DecimalField(decimal_places=4, max_digits=12)),
                ('purchased_at', models.DateField()),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='api.mutualfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='api.user')),
            ],
        ),
    ]
