# Generated by Django 4.2.23 on 2025-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mutualfund_mfholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='mf_schema_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
