# Generated by Django 4.2.23 on 2025-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_mutualfund_kuvera_name_alter_mutualfund_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutualfund",
            name="expense_ratio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
