# Generated by Django 4.2.23 on 2025-07-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mutualfund_mf_schema_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='isin_growth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='latest_nav',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='latest_nav_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
