# Generated by Django 4.2.23 on 2025-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mutualfund_isin_growth_mutualfund_latest_nav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='nav_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
