# Generated by Django 4.2.23 on 2025-08-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_equitytaxrates"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutualfund",
            name="kuvera_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mutualfund",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
