# Generated by Django 4.2.23 on 2025-07-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mutualfund_nav_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundHistoricalNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin_growth', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'unique_together': {('isin_growth', 'date')},
            },
        ),
    ]
