# Generated by Django 4.2.23 on 2025-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_mutualfund_kuvera_slug_mutualfund_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutualfund",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
