# Generated by Django 4.2.23 on 2025-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_mutualfund_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
