# Generated by ChatGPT migration
from django.db import migrations, models
import django.db.models.deletion


def create_primary_accounts_and_assign_holdings(apps, schema_editor):
    User = apps.get_model('api', 'User')
    Account = apps.get_model('api', 'Account')
    MFHolding = apps.get_model('api', 'MFHolding')

    for user in User.objects.all():
        # Ensure user has at least one account; if not, create Primary
        accounts = Account.objects.filter(user=user)
        primary = accounts.filter(is_primary=True).first()
        if not accounts.exists():
            primary = Account.objects.create(user=user, name='Primary', is_primary=True)
        elif not primary:
            # Promote the earliest account as primary
            primary = accounts.order_by('created_at', 'id').first()
            primary.is_primary = True
            primary.save(update_fields=['is_primary'])

        # Assign holdings without account to primary
        MFHolding.objects.filter(user=user, account__isnull=True).update(account=primary)


def noop_reverse(apps, schema_editor):
    # No safe reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_reset_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.user')),
            ],
            options={
                'ordering': ['user', '-is_primary', 'created_at', 'id'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='mfholding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='api.account'),
        ),
        migrations.RunPython(create_primary_accounts_and_assign_holdings, noop_reverse),
    ]
